// Code generated by MockGen. DO NOT EDIT.
// Source: card/db_types.go

// Package mock is a generated GoMock package.
package mock

import (
	card "marveldigital/tag-reader-server/card"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/iris-contrib/go.uuid"
	bbolt "go.etcd.io/bbolt"
)

// MockICardDB is a mock of ICardDB interface.
type MockICardDB struct {
	ctrl     *gomock.Controller
	recorder *MockICardDBMockRecorder
}

// MockICardDBMockRecorder is the mock recorder for MockICardDB.
type MockICardDBMockRecorder struct {
	mock *MockICardDB
}

// NewMockICardDB creates a new mock instance.
func NewMockICardDB(ctrl *gomock.Controller) *MockICardDB {
	mock := &MockICardDB{ctrl: ctrl}
	mock.recorder = &MockICardDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICardDB) EXPECT() *MockICardDBMockRecorder {
	return m.recorder
}

// CheckAdminLogin mocks base method.
func (m *MockICardDB) CheckAdminLogin(id, pw string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAdminLogin", id, pw)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckAdminLogin indicates an expected call of CheckAdminLogin.
func (mr *MockICardDBMockRecorder) CheckAdminLogin(id, pw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAdminLogin", reflect.TypeOf((*MockICardDB)(nil).CheckAdminLogin), id, pw)
}

// ReadCardFilekey mocks base method.
func (m *MockICardDB) ReadCardFilekey(cardId []byte) ([]byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCardFilekey", cardId)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadCardFilekey indicates an expected call of ReadCardFilekey.
func (mr *MockICardDBMockRecorder) ReadCardFilekey(cardId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCardFilekey", reflect.TypeOf((*MockICardDB)(nil).ReadCardFilekey), cardId)
}

// UpdateCardCTR mocks base method.
func (m *MockICardDB) UpdateCardCTR(cardId, ctr []byte, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCardCTR", cardId, ctr, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCardCTR indicates an expected call of UpdateCardCTR.
func (mr *MockICardDBMockRecorder) UpdateCardCTR(cardId, ctr, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCardCTR", reflect.TypeOf((*MockICardDB)(nil).UpdateCardCTR), cardId, ctr, status)
}

// MockIBucket is a mock of IBucket interface.
type MockIBucket struct {
	ctrl     *gomock.Controller
	recorder *MockIBucketMockRecorder
}

// MockIBucketMockRecorder is the mock recorder for MockIBucket.
type MockIBucketMockRecorder struct {
	mock *MockIBucket
}

// NewMockIBucket creates a new mock instance.
func NewMockIBucket(ctrl *gomock.Controller) *MockIBucket {
	mock := &MockIBucket{ctrl: ctrl}
	mock.recorder = &MockIBucketMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBucket) EXPECT() *MockIBucketMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockIBucket) Delete(key []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIBucketMockRecorder) Delete(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIBucket)(nil).Delete), key)
}

// ForEach mocks base method.
func (m *MockIBucket) ForEach(fn func([]byte, []byte) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForEach", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForEach indicates an expected call of ForEach.
func (mr *MockIBucketMockRecorder) ForEach(fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForEach", reflect.TypeOf((*MockIBucket)(nil).ForEach), fn)
}

// Get mocks base method.
func (m *MockIBucket) Get(key []byte) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockIBucketMockRecorder) Get(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIBucket)(nil).Get), key)
}

// Put mocks base method.
func (m *MockIBucket) Put(key, value []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockIBucketMockRecorder) Put(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockIBucket)(nil).Put), key, value)
}

// Stats mocks base method.
func (m *MockIBucket) Stats() bbolt.BucketStats {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats")
	ret0, _ := ret[0].(bbolt.BucketStats)
	return ret0
}

// Stats indicates an expected call of Stats.
func (mr *MockIBucketMockRecorder) Stats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockIBucket)(nil).Stats))
}

// MockITx is a mock of ITx interface.
type MockITx struct {
	ctrl     *gomock.Controller
	recorder *MockITxMockRecorder
}

// MockITxMockRecorder is the mock recorder for MockITx.
type MockITxMockRecorder struct {
	mock *MockITx
}

// NewMockITx creates a new mock instance.
func NewMockITx(ctrl *gomock.Controller) *MockITx {
	mock := &MockITx{ctrl: ctrl}
	mock.recorder = &MockITxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITx) EXPECT() *MockITxMockRecorder {
	return m.recorder
}

// Bucket mocks base method.
func (m *MockITx) Bucket(name []byte) card.IBucket {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bucket", name)
	ret0, _ := ret[0].(card.IBucket)
	return ret0
}

// Bucket indicates an expected call of Bucket.
func (mr *MockITxMockRecorder) Bucket(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bucket", reflect.TypeOf((*MockITx)(nil).Bucket), name)
}

// CreateBucketIfNotExists mocks base method.
func (m *MockITx) CreateBucketIfNotExists(name []byte) (card.IBucket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBucketIfNotExists", name)
	ret0, _ := ret[0].(card.IBucket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBucketIfNotExists indicates an expected call of CreateBucketIfNotExists.
func (mr *MockITxMockRecorder) CreateBucketIfNotExists(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBucketIfNotExists", reflect.TypeOf((*MockITx)(nil).CreateBucketIfNotExists), name)
}

// MockIDB is a mock of IDB interface.
type MockIDB struct {
	ctrl     *gomock.Controller
	recorder *MockIDBMockRecorder
}

// MockIDBMockRecorder is the mock recorder for MockIDB.
type MockIDBMockRecorder struct {
	mock *MockIDB
}

// NewMockIDB creates a new mock instance.
func NewMockIDB(ctrl *gomock.Controller) *MockIDB {
	mock := &MockIDB{ctrl: ctrl}
	mock.recorder = &MockIDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDB) EXPECT() *MockIDBMockRecorder {
	return m.recorder
}

// Batch mocks base method.
func (m *MockIDB) Batch(fn func(card.ITx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Batch", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Batch indicates an expected call of Batch.
func (mr *MockIDBMockRecorder) Batch(fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Batch", reflect.TypeOf((*MockIDB)(nil).Batch), fn)
}

// Close mocks base method.
func (m *MockIDB) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIDBMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIDB)(nil).Close))
}

// Update mocks base method.
func (m *MockIDB) Update(fn func(card.ITx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIDBMockRecorder) Update(fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIDB)(nil).Update), fn)
}

// View mocks base method.
func (m *MockIDB) View(fn func(card.ITx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "View", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// View indicates an expected call of View.
func (mr *MockIDBMockRecorder) View(fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "View", reflect.TypeOf((*MockIDB)(nil).View), fn)
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Since mocks base method.
func (m *MockClock) Since(t time.Time) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Since", t)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Since indicates an expected call of Since.
func (mr *MockClockMockRecorder) Since(t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Since", reflect.TypeOf((*MockClock)(nil).Since), t)
}

// MockUUID is a mock of UUID interface.
type MockUUID struct {
	ctrl     *gomock.Controller
	recorder *MockUUIDMockRecorder
}

// MockUUIDMockRecorder is the mock recorder for MockUUID.
type MockUUIDMockRecorder struct {
	mock *MockUUID
}

// NewMockUUID creates a new mock instance.
func NewMockUUID(ctrl *gomock.Controller) *MockUUID {
	mock := &MockUUID{ctrl: ctrl}
	mock.recorder = &MockUUIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUUID) EXPECT() *MockUUIDMockRecorder {
	return m.recorder
}

// NewV4 mocks base method.
func (m *MockUUID) NewV4() (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewV4")
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewV4 indicates an expected call of NewV4.
func (mr *MockUUIDMockRecorder) NewV4() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewV4", reflect.TypeOf((*MockUUID)(nil).NewV4))
}
